// Tipo legacy para datos estáticos — los IDs son string en este archivo
// La DB usa number. Este archivo se mantiene solo como fallback de imágenes de categorías.
type LegacyProduct = {
  id: string | number
  name: string
  slug: string
  price: number
  originalPrice?: number
  category: string
  subcategory?: string
  images: string[]
  description: string
  sizes?: string[]
  colors?: string[]
  inStock: boolean
  featured: boolean
  badge?: string
}

export const products: LegacyProduct[] = [
  // ── MAQUILLAJE / ACCESORIOS DAMA ──
  {
    id: '1',
    name: '2 en 1 Labial SHEGLAM',
    slug: '2-en-1-labial-sheglam',
    price: 12,
    category: 'accesorios',
    subcategory: 'maquillaje',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2F7d881df9-9c31-5aa8-902c-e34b5f080d8b.jpeg'],
    description: '2-in-1 Lip Set (Liner & Gloss) — El dúo dinámico que tus labios necesitan. Delineador y gloss en un solo producto para un look perfecto todo el día.',
    inStock: true,
    featured: false,
    badge: 'Nuevo',
  },
  {
    id: '2',
    name: 'Blush SHEGLAM Jelly',
    slug: 'blush-sheglam-jelly',
    price: 15,
    category: 'accesorios',
    subcategory: 'maquillaje',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2F78a37500-f578-511c-9997-369f7da2fb19.jpeg'],
    description: 'SHEGLAM Jelly Blush — Mejillas con un toque jugoso. Rubor de textura gelatinosa que aporta color natural y duradero. Fácil de difuminar.',
    inStock: true,
    featured: false,
    badge: 'Nuevo',
  },
  {
    id: '3',
    name: 'Alfombrilla Limpia Brochas',
    slug: 'alfombrilla-limpia-brochas',
    price: 5,
    category: 'accesorios',
    subcategory: 'herramientas',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2Fbbc5a1ac-948c-5902-85fa-61b99eee898d.jpeg'],
    description: 'Alfombrilla texturizada para limpiar tus brochas de maquillaje de forma eficiente. Elimina residuos de productos con facilidad.',
    inStock: true,
    featured: false,
  },
  {
    id: '4',
    name: 'Almohadilla Skincare',
    slug: 'almohadilla-skincare',
    price: 5,
    category: 'accesorios',
    subcategory: 'skincare',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2F323815a1-cfe3-5241-844e-8a7d4d62160b.jpeg'],
    description: 'Cuida tu piel y el planeta. Almohadillas reutilizables de skincare. Dile adiós a los discos de algodón desechables. Suaves, ecológicas y lavables.',
    inStock: true,
    featured: false,
    badge: 'Nuevo',
  },

  // ── ROPA DAMA ──
  {
    id: '5',
    name: '3 Piezas Blanco (Conjunto)',
    slug: '3-piezas-blanco',
    price: 35,
    category: 'dama',
    subcategory: 'conjuntos',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2F26ea7308-f84b-5d9c-bf8a-658f03d36c2d.jpeg'],
    description: 'Conjunto de 3 piezas en color blanco. Elegante y versátil, perfecto para cualquier ocasión. Tela de alta calidad y corte favorecedor.',
    inStock: true,
    featured: true,
    badge: 'Nuevo',
  },
  {
    id: '6',
    name: 'Body Dama Talla M',
    slug: 'body-dama-talla-m',
    price: 15,
    category: 'dama',
    subcategory: 'bodys',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2F296ae807-3494-5c2d-8d56-571a12eba9b2.jpeg'],
    description: 'Body para dama en talla M. Diseño moderno y cómodo, ideal para usar solo o combinado. Tela suave y de calidad.',
    sizes: ['M'],
    inStock: true,
    featured: false,
  },
  {
    id: '7',
    name: 'Body Dama Talla S',
    slug: 'body-dama-talla-s',
    price: 15,
    category: 'dama',
    subcategory: 'bodys',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2F7a40e103-a704-56b6-bdf4-db868ef5ad93.jpeg'],
    description: 'Body para dama en talla S. Diseño moderno y cómodo, ideal para usar solo o combinado. Tela suave y de calidad.',
    sizes: ['S'],
    inStock: true,
    featured: false,
  },
  {
    id: '8',
    name: 'Camisa Dama Medio Lado',
    slug: 'camisa-dama-medio-lado',
    price: 15,
    category: 'dama',
    subcategory: 'camisas',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2F7921f3e6-6d2f-55e6-a083-684741e528a7.jpeg'],
    description: 'Camisa de dama con diseño asimétrico medio lado. Estilo moderno y actual, perfecta para looks casuales o semi-formales.',
    inStock: true,
    featured: true,
  },
  {
    id: '9',
    name: 'Camisa Tirantes',
    slug: 'camisa-tirantes',
    price: 15,
    category: 'dama',
    subcategory: 'camisas',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2F78bacd09-1105-5b67-a188-74c1306d0d34.jpeg'],
    description: 'Camisa de tirantes para dama. Ligera, fresca y versátil. Ideal para el calor venezolano. Combina con todo.',
    inStock: true,
    featured: false,
  },
  {
    id: '10',
    name: 'Camiseta Gym',
    slug: 'camiseta-gym',
    price: 15,
    category: 'dama',
    subcategory: 'deportiva',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2F07a87145-c1bc-507c-9c4a-e616403876f7.jpeg'],
    description: 'Camiseta deportiva para gym. Tela de secado rápido, ligera y cómoda. Perfecta para tus entrenamientos diarios.',
    inStock: true,
    featured: false,
  },
  {
    id: '11',
    name: 'Camiseta Manga Larga',
    slug: 'camiseta-manga-larga',
    price: 15,
    category: 'dama',
    subcategory: 'camisetas',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2F5c415e8b-d983-57f2-aaf4-a59a77b49d5c.jpeg'],
    description: 'Camiseta de manga larga para dama. Tela suave y cómoda, perfecta para los días frescos.',
    inStock: true,
    featured: false,
  },
  {
    id: '12',
    name: 'Camiseta Roja, Negra y Blanca',
    slug: 'camiseta-roja-negra-blanca',
    price: 12,
    category: 'dama',
    subcategory: 'camisetas',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2F33eaffaa-8e51-5082-875f-df65fca8f0b8.jpeg'],
    description: 'Camiseta en colores rojo, negro y blanco. Diseño llamativo y moderno. Tela cómoda de uso diario.',
    inStock: true,
    featured: false,
    badge: 'Oferta',
  },
  {
    id: '13',
    name: 'Camisetas Blanca, Marrón y Negra',
    slug: 'camisetas-blanca-marron-negra',
    price: 12,
    category: 'dama',
    subcategory: 'camisetas',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2F75809e84-040c-5f41-82bf-a5b347431736.jpeg'],
    description: 'Pack de camisetas en colores blanco, marrón y negro. Básicos esenciales para cualquier guardarropa. Tela suave de alta calidad.',
    inStock: true,
    featured: false,
    badge: 'Oferta',
  },

  // ── CABALLERO ──
  {
    id: '14',
    name: 'Camisa Polo Negra',
    slug: 'camisa-polo-negra',
    price: 22,
    category: 'caballero',
    subcategory: 'polos',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2Fd3e246ed-93f3-5ea6-a00a-f5b2a471cfef.jpeg'],
    description: 'Camisa polo negra para caballero. Tallas disponibles: L y XL. Tela piqué de alta calidad, fresca y elegante. Perfecta para cualquier ocasión.',
    sizes: ['L', 'XL'],
    inStock: true,
    featured: true,
  },

  // ── ACCESORIOS ──
  {
    id: '15',
    name: 'Argollas',
    slug: 'argollas',
    price: 3,
    category: 'accesorios',
    subcategory: 'joyería',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2F50e11c7a-db5f-50f8-a969-3cbfd96ddc51.jpeg'],
    description: 'Argollas elegantes para dama. Accesorio esencial que complementa cualquier look. Disponibles en varios diseños.',
    inStock: true,
    featured: false,
  },
  {
    id: '16',
    name: 'Cadena con Inicial',
    slug: 'cadena-con-inicial',
    price: 7,
    category: 'accesorios',
    subcategory: 'joyería',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2F6aed9951-bf78-5f40-af43-37d85765d956.jpeg'],
    description: 'Cadena fina con inicial personalizada. El regalo perfecto o el accesorio que añade un toque único a tu look. Acabado dorado de calidad.',
    inStock: true,
    featured: true,
    badge: 'Nuevo',
  },
  {
    id: '17',
    name: 'Caja Portátil Joyería',
    slug: 'caja-portatil-joyeria',
    price: 6,
    category: 'accesorios',
    subcategory: 'organización',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2F77d89df9-23f8-5956-9314-2ef15115b2f9.jpeg'],
    description: 'Caja portátil para organizar y transportar tu joyería con seguridad. Compacta, elegante y práctica para viajes o uso diario.',
    inStock: true,
    featured: false,
  },
  {
    id: '18',
    name: 'Cartera Coach Top Quality',
    slug: 'cartera-coach-top-quality',
    price: 35,
    category: 'accesorios',
    subcategory: 'carteras',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2F518a07ba-a36b-56cc-93eb-a60861cd80b7.jpeg'],
    description: 'Cartera Coach de top quality. Diseño funcional y espacioso para tu día a día. Detalle único y acabados de primera.',
    colors: ['Negro', 'Beige'],
    inStock: true,
    featured: true,
    badge: 'Premium',
  },
  {
    id: '19',
    name: 'Cartera Parchita Negra',
    slug: 'cartera-parchita-negra',
    price: 35,
    category: 'accesorios',
    subcategory: 'carteras',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2F9ce7d63d-4c7b-5b05-a3b5-6df9d84b8d1e.jpeg'],
    description: 'Cartera Parchita en color negro. Top quality, diseño moderno con estampado exclusivo. Espaciosa y versátil.',
    colors: ['Negro'],
    inStock: true,
    featured: false,
    badge: 'Premium',
  },
  {
    id: '20',
    name: 'Cartera Parchita Roja',
    slug: 'cartera-parchita-roja',
    price: 35,
    category: 'accesorios',
    subcategory: 'carteras',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2F91139245-4cd9-5bb9-bd9c-5f70cd40e5a1.jpeg'],
    description: 'Cartera Parchita en color rojo. Top quality, diseño moderno con estampado exclusivo. Espaciosa y llamativa.',
    colors: ['Rojo'],
    inStock: true,
    featured: true,
    badge: 'Premium',
  },

  // ── PERFUMES ──
  {
    id: '21',
    name: '9 PM 3.4 Oz EDP Men',
    slug: '9-pm-edp-men',
    price: 50,
    category: 'perfumes',
    subcategory: 'masculino',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2Fa518207f-2d36-57f3-bb62-b9c920f37cf4.jpeg'],
    description: '9 PM para hombre. Eau de Parfum 3.4 oz. Fragancia intensa y seductora para la noche. Notas amaderadas y especiadas de larga duración.',
    inStock: true,
    featured: true,
    badge: 'Premium',
  },
  {
    id: '22',
    name: '9 PM Rebel 3.4 Oz EDP Unisex',
    slug: '9-pm-rebel-edp-unisex',
    price: 55,
    category: 'perfumes',
    subcategory: 'unisex',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2Fd5dc2ab0-3a23-5bd1-9d3e-01958889b8dd.jpeg'],
    description: '9 PM Rebel Unisex. Eau de Parfum 3.4 oz. Fragancia audaz y contemporánea para él y para ella. Rebelde, única y sofisticada.',
    inStock: true,
    featured: true,
    badge: 'Premium',
  },
  {
    id: '23',
    name: 'Afnan 9 AM Dive Unisex 3.4 Oz EDP',
    slug: 'afnan-9-am-dive-unisex',
    price: 50,
    category: 'perfumes',
    subcategory: 'unisex',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2Fcae1a9c8-c70b-58e8-8790-2a37d6f1211a.jpeg'],
    description: 'Afnan 9 AM Dive Unisex. Eau de Parfum 3.4 oz. Fragancia fresca y acuática para el día. Ideal para cualquier ocasión.',
    inStock: true,
    featured: false,
    badge: 'Premium',
  },
  {
    id: '24',
    name: 'Amber Oud Gold Edition 4.0 Oz EDP Men',
    slug: 'amber-oud-gold-edition',
    price: 70,
    category: 'perfumes',
    subcategory: 'masculino',
    images: ['https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2F97f398e7-0a1e-5193-8077-8b1d25271cae.jpeg'],
    description: 'Amber Oud Gold Edition para hombre. Eau de Parfum 4.0 oz. Fragancia lujosa con notas de oud, ámbar y especias orientales. El perfume de los que destacan.',
    inStock: true,
    featured: true,
    badge: 'Premium',
  },
]

export const getFeatured = () => products.filter(p => p.featured)
export const getByCategory = (cat: string) => products.filter(p => p.category === cat)
export const getBySlug = (slug: string) => products.find(p => p.slug === slug)
export const getRelated = (product: { id: string | number; category: string }) =>
  products.filter(p => p.category === product.category && p.id !== product.id).slice(0, 4)

export const categories = [
  { id: 'dama',       label: 'Dama',       image: 'https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2F7921f3e6-6d2f-55e6-a083-684741e528a7.jpeg' },
  { id: 'caballero',  label: 'Caballero',  image: 'https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2Fd3e246ed-93f3-5ea6-a00a-f5b2a471cfef.jpeg' },
  { id: 'accesorios', label: 'Accesorios', image: 'https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2F518a07ba-a36b-56cc-93eb-a60861cd80b7.jpeg' },
  { id: 'perfumes',   label: 'Perfumes',   image: 'https://imgproxy.treinta.co/sig/size:3840:::/quality:75/plain/https%3A%2F%2Fus-east-1-prod-treinta-assets-bucket.s3.amazonaws.com%2Fa518207f-2d36-57f3-bb62-b9c920f37cf4.jpeg' },
]
